### ISSUE TITLE
custom font not used on diff view

### ISSUE THREAD

**Issue by terinjokes** [StylishThemes/GitHub-Dark-Script#17]
The custom font I've chosen doesn't seem to be used in diff views, the default "Menlo" is used instead.

**Comment by Mottie** [comment]
Hi @terinjokes!

Is the custom font installed on your system? The script can not load external fonts due to [GitHub's CSP](https://github.com/blog/1477-content-security-policy).

Also, when adding a font name, do not include quotes as the style auto-wraps all font names in quotes in case the name contains a space.

**Comment by terinjokes** [comment]
@Mottie Yes, the custom font is installed, and it used when viewing a file, in the commit message on a commit screen, but not when looking at a diff view (the changes in a commit or PR)

**Comment by Mottie** [comment]
Ahh ok, I found the problem... incoming update!

**Comment by Mottie** [comment]
Please use the force update button to get the script to grab the changes :grin:

**Comment by terinjokes** [comment]
Awesome, thanks!
