### ISSUE TITLE
Safari Tampermonkey support

### ISSUE THREAD

**Issue by mikelemoscentrica** [StylishThemes/GitHub-Dark-Script#63]
I'd love to have GitHub in dark mode when using Safari. Preferably installed as a script in Tampermonkey.

**Comment by the-j0k3r** [comment]
Hello and thank you for reaching out with this request =)

Ive no idea how old this is but in https://github.com/StylishThemes/GitHub-Dark-Script/wiki/Install it says tampermonkey doesnt currently work on safari, But here https://tampermonkey.net/?browser=safari it doesnt say any such thing.

So, best bet is intall it and test, if doesnt work, consider looking at tampermonkey dev team to get it to work.

**Comment by silverwind** [comment]
The issue with Safari is https://github.com/StylishThemes/GitHub-Dark-Script/issues/13. GitHub is a site that uses CSP which prevents any userscript from running, to my knowledge. Userscript engines could probably workaround by stripping the CSP header before the site loads, but that can compromise security.

**Comment by xt0rted** [comment]
As far as I know the only way to use user styles in Safari right now is with https://cascadea.app/. This has its own set of issues though because it doesn't support UserCSS, but the author has said on Twitter that it's being worked on. The CSP issue was fixed in Edge but remains in Safari the last time I tried it (4-5 months ago).

**Comment by silverwind** [comment]
Closing in favor of https://github.com/StylishThemes/GitHub-Dark-Script/issues/13.
