### ISSUE TITLE
Could you please add gitlab theme as same as this?

### ISSUE THREAD

**Issue by roket1428** [StylishThemes/GitHub-Dark-Script#65]
I really liked your theme [who you are anyway. :)]. But it would be fantastic if you could add gitlab support-ish thing? I mean this colorscheme looks perfect. Just wanna same colorscheme in gitlab too. I hope you will do that. Yours sincerely.

**Comment by the-j0k3r** [comment]
Hello @roket1428 and thank you for reaching out to us with this request.

I cant say if this will ever be done or not in this repo. Personally I dont use Gitlab, so my motivation to support it is none at this time though I dont speak for everyone here in that regard. 

I know of a good working theme for Gitlab you may like in the meanwhile https://gitlab.com/vednoc/dark-gitlab Maybe that can be used one day with this script?

**Comment by roket1428** [comment]
Actually, I'm using that before you mentioned. :) But I hope you'll make something for that too. :)

**Comment by silverwind** [comment]
No interest here too, not using GitLab. I do use [gitea](https://github.com/go-gitea/gitea), maybe I'll do a theme for it someday.

**Comment by vednoc** [comment]
Hey @roket1428, with a little bit of work you can customize just about everything on Dark-GitLab theme. Things won't look exactly like on GitHub due to the obvious differences in design, but the colors should be pretty spot-on.

With these settings I was able to get fairly close to how GitHub-Dark looks.
![image](https://user-images.githubusercontent.com/18245694/60387313-72ec1f00-9aa1-11e9-8a1c-9043b8ce251a.png)

**Comment by the-j0k3r** [comment]
Shame you cant share settings from stylus only like in screenie, or, maybe export the theme with those settings from stylus and share that. Just a thought. 

Alo Gitlab dark by mew, works on Gitea or so it did in a quick test.
