### ISSUE TITLE
Inverted user avatars on Network tab

### ISSUE THREAD

**Issue by Lordmau5** [StylishThemes/GitHub-Dark-Script#71]
* **Browser**: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* **Operating System**: Windows 10 1903
* **Link to page with the issue**: https://github.com/gta-chaos-mod/ASI-script/network
* **Screenshot**:
![image](https://user-images.githubusercontent.com/1345036/64922548-c03e7980-d7d0-11e9-9969-1e0046d856d7.png)

**Comment by the-j0k3r** [comment]
@Lordmau5 This is intentional, partially because the elements are inside a canvas and there is no other way to style them, other than to invert the canvas.

See https://github.com/StylishThemes/GitHub-Dark/issues/583 and https://github.com/StylishThemes/GitHub-Dark/issues/961 but however this is how it remains.

If you know a better way to handle this please come forth ;)

**Comment by Lordmau5** [comment]
Hmm yeah, I noticed they were using a canvas which seems... weird to work with, hehe

Also, my bad for not checking whether or not there was an issue about this already.

**Comment by the-j0k3r** [comment]
> Also, my bad for not checking whether or not there was an issue about this already.

No probs,

Ill close the ticket now, but feel free to come up with better suggestions or a JS fix, maybe @raitaroh who opened one of the issue tickets above has some clews how to in the script version.
