### ISSUE TITLE
White repo header

### ISSUE THREAD

**Issue by KaKi87** [StylishThemes/GitHub-Dark-Script#75]
Hello,

All repo tabs except *Code* and *Insights* have white headers :

![2020-02-08 09_14_14-Issues · StylishThemes_GitHub-Dark-Script](https://user-images.githubusercontent.com/21284089/74081893-2794e880-4a54-11ea-9c4e-639d4fdf21dd.png)

However, the white header may stay when you switch from any tab to *Code* or *Insights* since it's a JS redirection.

Here's the root cause :

![2020-02-08 09_26_46-Security Advisories · StylishThemes_GitHub-Dark-Script](https://user-images.githubusercontent.com/21284089/74081992-7ee78880-4a55-11ea-9fd4-ce493e293871.png)

Thanks

**Comment by the-j0k3r** [comment]
Please force a style update in GitHub Dark Script, this issue was tracked/fixed upstream  in https://github.com/StylishThemes/GitHub-Dark/issues/1057

![image](https://cloud.githubusercontent.com/assets/136959/22908590/022f56d8-f215-11e6-954c-decc9ecbd259.png)

At bottom click **force update style**

Also notice the script is buggy see https://github.com/StylishThemes/GitHub-Dark-Script/issues/73#issuecomment-553383622 it will also affect other areas though maybe not this one.

In any case I suggest you use [GitHub Dark + Stylus](https://github.com/StylishThemes/GitHub-Dark#installation) and discontinue using GitHub-Dark-Script until those issues are resolved.
You will also benefit from a better user out of box experience with  [GitHub Dark + Stylus](https://github.com/StylishThemes/GitHub-Dark#installation).

Hope this helps. =)

**Comment by KaKi87** [comment]
Oh I'm sorry I didn't noticed that the script and the style were on separate repositories. Thanks

**Comment by the-j0k3r** [comment]
Yes the script just loads the style, this script was pre-stylus and tbh is obsolete IMHO.
